host = 127.0.0.1
port = 11333
add_headers = always

[dkim]
enabled = false

[header]
bar = X-Rspamd-Bar
report = X-Rspamd-Report
score = X-Rspamd-Score

[check]
authenticated=false
private_ip=true
local_ip=true
relay=false

[reject]
spam = true
message = Detected as spam
authenticated=false

[rmilter_headers]
;enabled = true

[spambar]
;positive = +
;negative = -
;neutral = /
